x-google-marketplace:
#* schema level properties
  schemaVersion: v2

# Additional properties for test/verify. Reference:
# https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/verification-integration.md

# this file will be applied together with the normal schema.yaml, to populate chart values during verification.

properties:
  name:
    type: string
    default: gateway
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: virtru
    x-google-marketplace:
      type: NAMESPACE
  gatewayHostname:
    type: string
    default: gateway-development-verify.virtru.com
    x-google-marketplace:
      type: STRING
  gatewayApiTokenName:
    type: string
    default: fake-gatewayApiTokenName
    x-google-marketplace:
      type: STRING
  gatewayApiSecret:
    type: string
    default: fake-gatewayApiSecret
    x-google-marketplace:
      type: STRING
  gatewayFlow:
    type: string
    default: "Outbound - Data Loss Prevention"
    x-google-marketplace:
      type: STRING
  primaryMailingDomain:
    type: string
    default: example.com
    x-google-marketplace:
      type: STRING
  amplitudeToken:
    type: string
    default: fake-amplitudeToken
    x-google-marketplace:
      type: STRING
  numberOfLicenses:
    type: string
    default: "25"
    x-google-marketplace:
      type: STRING
  reportingSecret:
    type: string
    default: "gs://cloud-marketplace-tools/reporting_secrets/fake_reporting_secret.yaml"
    x-google-marketplace:
      type: REPORTING_SECRET
  cse.enabled:
    title: Include Google Client Side Encryption Key Management Server (KMS)
    description: Standard Plan Required
    type: boolean
    enum:
      - true
      - false
    default: true
  cse.appSecrets.hmac.tokenId:
    title: Google Client Side Encryption KMS Token ID
    description: Token ID Provided by Virtru. Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "fake-id"
  cse.appSecrets.hmac.tokenSecret:
    title: Google Client Side Encryption KMS Token Secret
    description: Token Secret Provided by Virtru. Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "ZmFrZS1kYXRhCg=="
  cse.appSecrets.secretKey:
    title: Google Client Side Encryption KMS Secret Key
    description: Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "fake-key:ZmFrZS1kYXRhCg=="
  cse.appSecrets.ssl.certificate:
    title: Google Client Side Encryption SSL Certificate
    description: Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "ZmFrZS1kYXRhCg=="
  cse.appSecrets.ssl.privateKey:
    title: Google Client Side Encryption SSL Private Key
    description: Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "ZmFrZS1kYXRhCg=="
  cse.appConfig.jwksAuthzIssuers:
    title: Authz Issuers
    description: Base64-encoded authz issuer json. Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "iZmFrZS1kYXRhCg=="
  cse.appConfig.jwksAuthnIssuers:
    title: Authn Issuers
    description: Base64-encoded authn issuer json. Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "ZmFrZS1kYXRhCg=="
  cse.appConfig.jwtAud:
    title: Issuer Names
    description: Base64-encoded json containing issuer names. Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "ZmFrZS1kYXRhCg=="
  cse.appConfig.jwtKaclsUrl:
    title: Google Client Side Encryption URL
    description: Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "https://example.com"
  cse.ingress.host:
    title: Google Client Side Encryption Domain Name
    description: Leave blank if not deploying Google Client Side Encryption KMS
    type: string
    x-google-marketplace:
      type: STRING
    default: "example.com"
required:
- name
- namespace
- gatewayHostname
- gatewayApiTokenName
- gatewayApiSecret
- gatewayFlow
- primaryMailingDomain
- amplitudeToken
- pricingPlan
- numberOfLicenses
