apiVersion: v2
name: gateway
version: 1.3.1
dependencies:
- name: cse
  version: 0.6.0
  repository: https://virtru-corp.github.io/virtru-charts/
  condition: cse.enabled
- name: cks
  version: 0.6.1
  repository: https://virtru-corp.github.io/virtru-charts/
  condition: cks.enabled
