apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "virtru", "product_id": "gateway", "partner_name": "Virtru"}'
spec:
  descriptor:
    type: Gateway
    version: "{{ .Values.image.tag }}"
    description: >-
      Virtru is Google’s recommended data-centric security solution for Google Workspace. We provide email and file encryption with flexible access controls and actionable intelligence across data. Virtru complements your experience by adding a seamless layer of security and privacy on top of native Google capabilities.

      # Support
      * [Virtru Support](https://support.virtru.com/hc/en-us)
      * [Virtru Installation Guide](https://support.virtru.com/hc/en-us/sections/360012614693-Virtru-Google-Marketplace).
    links:
      - description: Virtru Support
        url: https://support.virtru.com/hc/en-us
      - description: Virtru Installation Guide
        url: https://support.virtru.com/hc/en-us/sections/360012614693-Virtru-Google-Marketplace
    notes: |-
      # Virtru Notes
      ## 1. Installation details:
      - Service: {{ include "gateway.fullname" . }}
      - Namespace: {{ .Release.Namespace }}

      ##2. Get the LoadBalancer IP and port
           NOTE: It may take a few minutes for the LoadBalancer IP to be available.
                 You can watch the status of by running 'kubectl get --namespace {{ .Release.Namespace }} svc -w {{ include "gateway.fullname" . }}'

      ## 3. Next Steps
      Please follow the [Virtru Installation Guide](https://support.virtru.com/hc/en-us/sections/360012614693-Virtru-Google-Marketplace)
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  addOwnerRef: true

  componentKinds:
  - group: apps
    kind: Deployment
  - group: ''
    kind: PersistentVolumeClaim
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: ConfigMap