apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
data:
  gateway-amplitude-api-key: {{ .Values.amplitudeToken | b64enc | quote }}
  gateway-api-token-name: {{ .Values.gatewayApiTokenName | b64enc | quote }}
  gateway-api-token-secret: {{ .Values.gatewayApiSecret | b64enc | quote }}
